version: 2

models:
  - name: order_products_prior
    columns:
      - name: order_id
        description: "The primary key for order products"
        tests:
          - not_null

  - name: user_features_1 
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - not_null   

  - name: user_features_2
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - not_null

  - name: up_features
    columns:
      - name: user_id
        description: "The primary key for up_features"
        tests:
          - not_null
      - name: product_id
        description: "The primary key for this table"
        tests:
          - not_null     
  
  - name: prd_features
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - not_null